### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by lfrodrigues** [baccenfutter/ldap_hopper#4]
Your code is fully compatible with python 3 except for the print statement. 

Could you please add so you have support for both python >=2.6 and python 3
```
from __future__ import print_function
```

**Comment by ri0t** [comment]
As far as i know, there are some unconnected repos that already have the py3-compat. If no one claims this in the next 5 days, i'm gonna contribute one. (I don't have any, but i like porting stuff from 2.x to 3 and like this repo in general) :-)

I'm also opting for adding a test suite and CI.  Once we have that, a core infrastructure certification might be interesting :D

**Comment by baccenfutter** [comment]
@ri0t I've invited you as a contributor. `master` is protected. I will gladly merge contributions in form of pull-requests, as long as they are in compliance with the WTFPL.

**Comment by baccenfutter** [comment]
@lfrodrigues I apologize for missing your post. Haven't given this repo too much attention in the past few years. This might change soon, as I will rely on it as a dependency in a couple of upcoming projects.

Is there anything specific you are relying on that I should know of or do you have any comments, suggestions etc, please feel welcome to create a few issues so we have it on our radar.

**Comment by baccenfutter** [comment]
Resolved by: #9
