### ISSUE TITLE
Needs nice batch of docstrings

### ISSUE THREAD

**Issue by ri0t** [baccenfutter/ldap_hopper#5]
https://github.com/baccenfutter/ldap_hopper/blob/9f8f29234f74b24213045c32a4e7b608c895c84a/ldap_hopper.py#L2

I personally made dunders extinct in my project (i just killed them wholesomely in my [last copyright update](https://github.com/ri0t/upright) ;) ) - any opinion on that?

**Comment by baccenfutter** [comment]
Not quite sure if I understand what you mean... Are you suggesting to remove it from the source? In that case I have zero objections. While at it we should add an according `LICENSE` I am thinking GPL2, other suggstions?

**Comment by ri0t** [comment]
Fine by me. I like AGPL but since you're coming from WTFPL, that would be quite drastic :D

**Comment by baccenfutter** [comment]
Perhaps it makes most sense to simply use what OpenLDAP uses as a license model?
- https://www.openldap.org/software/release/license.html

**Comment by baccenfutter** [comment]
@ri0t I've licensed this under a CC license and am now realizing there is this issue. Are you happy with the new licensing or is this issue resolved?
