### ISSUE TITLE
pack?

### ISSUE THREAD

**Issue by ri0t** [baccenfutter/ldap_hopper#6]
That part still necessary?
This package is already nicely posted on pypi.

It should be unproblematic to package a debian (or whatever) package, since this one is r'ly simple ;D

**Comment by baccenfutter** [comment]
What part exactly are you referring to?

**Comment by ri0t** [comment]
https://github.com/baccenfutter/ldap_hopper/tree/master/pack

**Comment by baccenfutter** [comment]
In fact, this is this script that built and uploaded the package you found on PyPI. In more recent projects I use a `Makefile` with a `build` and a `dist` target.

If you want to improve packaging and distribution, feel free to do so. If you supply improvements, I will happily merge, but we will need some way of (at least semi-)automatic packaging and distribution.

Nowadays, Github workflows exist and it would be feasible to fully automate packaging and distribution.

**Comment by baccenfutter** [comment]
Resolved by: #9
