### ISSUE TITLE
Undefined r in line 240

### ISSUE THREAD

**Issue by ri0t** [baccenfutter/ldap_hopper#7]
That won't work:

https://github.com/baccenfutter/ldap_hopper/blob/9f8f29234f74b24213045c32a4e7b608c895c84a/ldap_hopper.py#L240

Should it be `r_data` instead?

**Comment by baccenfutter** [comment]
Looks more like an indention fail:

https://github.com/baccenfutter/ldap_hopper/blob/9f8f29234f74b24213045c32a4e7b608c895c84a/ldap_hopper.py#L236-L241

**Comment by baccenfutter** [comment]
Resolved by: #9
